In [24]:
import pandas as pd
import os
import numpy as np

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [25]:
data_path = 'data'
input_csv_name = 'val.csv' 
ifile_name = os.path.join(data_path + os.sep + input_csv_name) #Raw SO scrapped data

In [26]:
df = pd.read_csv(ifile_name)
df

,Id,Body,CommentCount,LastEditDate,Score,Reputation,UpVotes,DownVotes,Views,QId,QAcceptedAnswerId,QBody
0,60026924,<p>You might simplify your piece to make it mo...,2,NaN,0,1678,131,50,109,60012940,60026924,<p>Given a structure like the following:</p>\n...
1,60013028,"<p>Use <a href=""https://pandas.pydata.org/pand...",0,NaN,0,423,27,14,87,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...
2,60013049,<p>Solution without <code>pandas</code>:</p>\n...,0,NaN,0,67907,1966,35,5948,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...
3,60013070,<p>You do not need to load the immense Panda l...,0,2020-02-01 00:55:41,2,695,55,5,87,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...
4,60013072,<p>Keeping part posters original software</p>\...,0,NaN,1,10876,714,1,925,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...
...,...,...,...,...,...,...,...,...,...,...,...,...
315,60022202,<p>Try:</p>\n\n<pre><code>df.groupby(['Gene na...,8,2020-02-03 17:42:01,3,111735,6882,268,5246,60022107,60022202,"<p>I have this dataframe(df), that looks like ..."
316,60022212,"<p>In your function, you're returning prime_fa...",4,NaN,2,640,117,5,68,60022139,60022212,"<p>I need a little help guys, I'm doing a proj..."
317,60022169,<p>Filter out character '-'-containing lines f...,0,NaN,4,6047,467,19,531,60022157,60022273,<p>I am trying to figure out how to write a fu...
318,60022210,"<p>I'd filter out while reading the file, not ...",0,2020-02-02 00:28:06,2,5574,625,2339,1000,60022157,60022273,<p>I am trying to figure out how to write a fu...
319,60022273,<p>Gwang-Jin Kim and Heap Overflow answers are...,4,2020-02-02 00:32:34,1,4588,211,39,464,60022157,60022273,<p>I am trying to figure out how to write a fu...

### BodyLength
For each answer, we get size of answer body in words

In [27]:
length_list = []
from src.body_util import clear_tags
datapoints = df.shape[0]
for i in range(datapoints): 
    answer_text = clear_tags(df['Body'][i])
    length_list.append(len(answer_text.split()))

df['BodyLength'] = length_list
df

,Id,Body,CommentCount,LastEditDate,Score,Reputation,UpVotes,DownVotes,Views,QId,QAcceptedAnswerId,QBody,BodyLength
0,60026924,<p>You might simplify your piece to make it mo...,2,NaN,0,1678,131,50,109,60012940,60026924,<p>Given a structure like the following:</p>\n...,17
1,60013028,"<p>Use <a href=""https://pandas.pydata.org/pand...",0,NaN,0,423,27,14,87,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,80
2,60013049,<p>Solution without <code>pandas</code>:</p>\n...,0,NaN,0,67907,1966,35,5948,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,45
3,60013070,<p>You do not need to load the immense Panda l...,0,2020-02-01 00:55:41,2,695,55,5,87,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,90
4,60013072,<p>Keeping part posters original software</p>\...,0,NaN,1,10876,714,1,925,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,60022202,<p>Try:</p>\n\n<pre><code>df.groupby(['Gene na...,8,2020-02-03 17:42:01,3,111735,6882,268,5246,60022107,60022202,"<p>I have this dataframe(df), that looks like ...",208
316,60022212,"<p>In your function, you're returning prime_fa...",4,NaN,2,640,117,5,68,60022139,60022212,"<p>I need a little help guys, I'm doing a proj...",31
317,60022169,<p>Filter out character '-'-containing lines f...,0,NaN,4,6047,467,19,531,60022157,60022273,<p>I am trying to figure out how to write a fu...,21
318,60022210,"<p>I'd filter out while reading the file, not ...",0,2020-02-02 00:28:06,2,5574,625,2339,1000,60022157,60022273,<p>I am trying to figure out how to write a fu...,55
319,60022273,<p>Gwang-Jin Kim and Heap Overflow answers are...,4,2020-02-02 00:32:34,1,4588,211,39,464,60022157,60022273,<p>I am trying to figure out how to write a fu...,93

### Code
For each answer, we calculate number of code blocks

In [28]:
codes_inline = []
codes_pre_line = []
codes_pre_count = []
datapoints = df.shape[0]
for i in range(datapoints): 
    answer_text = df['Body'][i]
    code_start = 0
    code_end = 0
    code_pre_line = 0 #Number of code blocks
    code_pre_count = 0 #Number of lines in code blocks
    code_inline = 0 #Number of inline code snippets
    while True:
        code_start = answer_text.find('<code>', code_end)
        if code_start == -1:
            break
        code_end = answer_text.find('</code>', code_start)
        code = answer_text[code_start: code_end+7]
        # Here, code is a string which is of the format <code>.....</code>
        if answer_text[code_start-5: code_start] == '<pre>':
            code_line = code.split('\n')
            code_line_count = len(code_line)-1 # Last line as </code>
            code_pre_line += code_line_count
            code_pre_count += 1
        else:
            code_inline += 1
    codes_inline.append(code_inline)
    codes_pre_line.append(code_pre_line)
    codes_pre_count.append(code_pre_count)

df['InlineCode'] = codes_inline
df['BlockCode'] = codes_pre_count
df['BlockCodeLine'] = codes_pre_line
df

,Id,Body,CommentCount,LastEditDate,Score,Reputation,UpVotes,DownVotes,Views,QId,QAcceptedAnswerId,QBody,BodyLength,InlineCode,BlockCode,BlockCodeLine
0,60026924,<p>You might simplify your piece to make it mo...,2,NaN,0,1678,131,50,109,60012940,60026924,<p>Given a structure like the following:</p>\n...,17,0,1,3
1,60013028,"<p>Use <a href=""https://pandas.pydata.org/pand...",0,NaN,0,423,27,14,87,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,80,0,4,12
2,60013049,<p>Solution without <code>pandas</code>:</p>\n...,0,NaN,0,67907,1966,35,5948,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,45,1,2,15
3,60013070,<p>You do not need to load the immense Panda l...,0,2020-02-01 00:55:41,2,695,55,5,87,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,90,1,0,0
4,60013072,<p>Keeping part posters original software</p>\...,0,NaN,1,10876,714,1,925,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,40,0,2,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,60022202,<p>Try:</p>\n\n<pre><code>df.groupby(['Gene na...,8,2020-02-03 17:42:01,3,111735,6882,268,5246,60022107,60022202,"<p>I have this dataframe(df), that looks like ...",208,0,4,19
316,60022212,"<p>In your function, you're returning prime_fa...",4,NaN,2,640,117,5,68,60022139,60022212,"<p>I need a little help guys, I'm doing a proj...",31,0,0,0
317,60022169,<p>Filter out character '-'-containing lines f...,0,NaN,4,6047,467,19,531,60022157,60022273,<p>I am trying to figure out how to write a fu...,21,0,1,1
318,60022210,"<p>I'd filter out while reading the file, not ...",0,2020-02-02 00:28:06,2,5574,625,2339,1000,60022157,60022273,<p>I am trying to figure out how to write a fu...,55,3,1,3
319,60022273,<p>Gwang-Jin Kim and Heap Overflow answers are...,4,2020-02-02 00:32:34,1,4588,211,39,464,60022157,60022273,<p>I am trying to figure out how to write a fu...,93,3,1,9

### Hyperlink
For each post, we calculate the number of links referenced

In [29]:
hyperlinks = []
datapoints = df.shape[0]
for i in range(datapoints):
    body = df['Body'][i]
    hyperlink_pos = -1
    hyperlink = 0
    while True:
        hyperlink_pos = body.find('<a href=', hyperlink_pos+1)
        if hyperlink_pos == -1:
            break
        hyperlink += 1
        # print(i, body[hyperlink_pos:hyperlink_pos + 50])
    hyperlinks.append(hyperlink)

df['Hyperlink'] = hyperlinks
df

,Id,Body,CommentCount,LastEditDate,Score,Reputation,UpVotes,DownVotes,Views,QId,QAcceptedAnswerId,QBody,BodyLength,InlineCode,BlockCode,BlockCodeLine,Hyperlink
0,60026924,<p>You might simplify your piece to make it mo...,2,NaN,0,1678,131,50,109,60012940,60026924,<p>Given a structure like the following:</p>\n...,17,0,1,3,0
1,60013028,"<p>Use <a href=""https://pandas.pydata.org/pand...",0,NaN,0,423,27,14,87,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,80,0,4,12,2
2,60013049,<p>Solution without <code>pandas</code>:</p>\n...,0,NaN,0,67907,1966,35,5948,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,45,1,2,15,0
3,60013070,<p>You do not need to load the immense Panda l...,0,2020-02-01 00:55:41,2,695,55,5,87,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,90,1,0,0,0
4,60013072,<p>Keeping part posters original software</p>\...,0,NaN,1,10876,714,1,925,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,40,0,2,12,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,60022202,<p>Try:</p>\n\n<pre><code>df.groupby(['Gene na...,8,2020-02-03 17:42:01,3,111735,6882,268,5246,60022107,60022202,"<p>I have this dataframe(df), that looks like ...",208,0,4,19,0
316,60022212,"<p>In your function, you're returning prime_fa...",4,NaN,2,640,117,5,68,60022139,60022212,"<p>I need a little help guys, I'm doing a proj...",31,0,0,0,0
317,60022169,<p>Filter out character '-'-containing lines f...,0,NaN,4,6047,467,19,531,60022157,60022273,<p>I am trying to figure out how to write a fu...,21,0,1,1,0
318,60022210,"<p>I'd filter out while reading the file, not ...",0,2020-02-02 00:28:06,2,5574,625,2339,1000,60022157,60022273,<p>I am trying to figure out how to write a fu...,55,3,1,3,0
319,60022273,<p>Gwang-Jin Kim and Heap Overflow answers are...,4,2020-02-02 00:32:34,1,4588,211,39,464,60022157,60022273,<p>I am trying to figure out how to write a fu...,93,3,1,9,1

### Edit
For each post, we check if it was edited

In [30]:
edits = []
datapoints = df.shape[0]
for i in range(datapoints):
    last_edit_date = df['LastEditDate'][i] # str or float (np.nan)
    if isinstance(last_edit_date, float):
        if np.isnan(last_edit_date):
            edits.append('0')
        else:
            edits.append('1')
    else:
        edits.append('1')
df['Edit'] = edits
df

,Id,Body,CommentCount,LastEditDate,Score,Reputation,UpVotes,DownVotes,Views,QId,QAcceptedAnswerId,QBody,BodyLength,InlineCode,BlockCode,BlockCodeLine,Hyperlink,Edit
0,60026924,<p>You might simplify your piece to make it mo...,2,NaN,0,1678,131,50,109,60012940,60026924,<p>Given a structure like the following:</p>\n...,17,0,1,3,0,0
1,60013028,"<p>Use <a href=""https://pandas.pydata.org/pand...",0,NaN,0,423,27,14,87,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,80,0,4,12,2,0
2,60013049,<p>Solution without <code>pandas</code>:</p>\n...,0,NaN,0,67907,1966,35,5948,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,45,1,2,15,0,0
3,60013070,<p>You do not need to load the immense Panda l...,0,2020-02-01 00:55:41,2,695,55,5,87,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,90,1,0,0,0,1
4,60013072,<p>Keeping part posters original software</p>\...,0,NaN,1,10876,714,1,925,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,40,0,2,12,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,60022202,<p>Try:</p>\n\n<pre><code>df.groupby(['Gene na...,8,2020-02-03 17:42:01,3,111735,6882,268,5246,60022107,60022202,"<p>I have this dataframe(df), that looks like ...",208,0,4,19,0,1
316,60022212,"<p>In your function, you're returning prime_fa...",4,NaN,2,640,117,5,68,60022139,60022212,"<p>I need a little help guys, I'm doing a proj...",31,0,0,0,0,0
317,60022169,<p>Filter out character '-'-containing lines f...,0,NaN,4,6047,467,19,531,60022157,60022273,<p>I am trying to figure out how to write a fu...,21,0,1,1,0,0
318,60022210,"<p>I'd filter out while reading the file, not ...",0,2020-02-02 00:28:06,2,5574,625,2339,1000,60022157,60022273,<p>I am trying to figure out how to write a fu...,55,3,1,3,0,1
319,60022273,<p>Gwang-Jin Kim and Heap Overflow answers are...,4,2020-02-02 00:32:34,1,4588,211,39,464,60022157,60022273,<p>I am trying to figure out how to write a fu...,93,3,1,9,1,1

### Label
For each post, we classify if it is the correct answer

In [31]:
labels = []
datapoints = df.shape[0]
for i in range(datapoints):
        
    answer_id = df['Id'][i] # int
    accepted_id = df['QAcceptedAnswerId'][i] # float (np.nan)
    if np.isnan(accepted_id):
        labels.append(np.nan)
    else:
        if answer_id == int(accepted_id):
            labels.append('1')
        else:
            labels.append('0')
df['Label'] = labels
df

,Id,Body,CommentCount,LastEditDate,Score,Reputation,UpVotes,DownVotes,Views,QId,QAcceptedAnswerId,QBody,BodyLength,InlineCode,BlockCode,BlockCodeLine,Hyperlink,Edit,Label
0,60026924,<p>You might simplify your piece to make it mo...,2,NaN,0,1678,131,50,109,60012940,60026924,<p>Given a structure like the following:</p>\n...,17,0,1,3,0,0,1
1,60013028,"<p>Use <a href=""https://pandas.pydata.org/pand...",0,NaN,0,423,27,14,87,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,80,0,4,12,2,0,0
2,60013049,<p>Solution without <code>pandas</code>:</p>\n...,0,NaN,0,67907,1966,35,5948,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,45,1,2,15,0,0,0
3,60013070,<p>You do not need to load the immense Panda l...,0,2020-02-01 00:55:41,2,695,55,5,87,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,90,1,0,0,0,1,0
4,60013072,<p>Keeping part posters original software</p>\...,0,NaN,1,10876,714,1,925,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,40,0,2,12,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,60022202,<p>Try:</p>\n\n<pre><code>df.groupby(['Gene na...,8,2020-02-03 17:42:01,3,111735,6882,268,5246,60022107,60022202,"<p>I have this dataframe(df), that looks like ...",208,0,4,19,0,1,1
316,60022212,"<p>In your function, you're returning prime_fa...",4,NaN,2,640,117,5,68,60022139,60022212,"<p>I need a little help guys, I'm doing a proj...",31,0,0,0,0,0,1
317,60022169,<p>Filter out character '-'-containing lines f...,0,NaN,4,6047,467,19,531,60022157,60022273,<p>I am trying to figure out how to write a fu...,21,0,1,1,0,0,0
318,60022210,"<p>I'd filter out while reading the file, not ...",0,2020-02-02 00:28:06,2,5574,625,2339,1000,60022157,60022273,<p>I am trying to figure out how to write a fu...,55,3,1,3,0,1,0
319,60022273,<p>Gwang-Jin Kim and Heap Overflow answers are...,4,2020-02-02 00:32:34,1,4588,211,39,464,60022157,60022273,<p>I am trying to figure out how to write a fu...,93,3,1,9,1,1,1

### Unigram + Bigram scores
First, we generate a corpus of well written answers

In [32]:
from src.ngram import gen_corpus
from os.path import exists

corpus_file = 'data/corpus.txt' #This is the output which will be generated
if input_csv_name == 'train.csv':
    gen_corpus(df[df.Label=='1'].Body.tolist(),corpus_file)
else:
    print ("NGram corpus only for train data")
    if not exists(corpus_file):
        raise Exception("No corpus present. Generate corpus with training data first")

NGram corpus only for train data

Now, we use the corpus file to generate a language model. Then we can calculate unigram and bigram costs

In [33]:
from src.ngram import make_language_model
from src.ngram import SENTENCE_BEGIN

unigram_cost, bigram_cost = make_language_model(corpus_file)

ug = []
bg = []

datapoints = df.shape[0]

for i in range(datapoints):
        line = df['Body'][i]
        # Unigram cost.
        grams=tuple(line)
        cost=0
        for j in range(len(grams)):
            cost+=unigram_cost(grams[j])
        cost=cost/len(grams)
        ug.append(cost)

        cost=bigram_cost(SENTENCE_BEGIN, grams[0])
        for j in range(1,len(grams)):
            cost+=bigram_cost(grams[j-1], grams[j])
        cost=cost/len(grams)
        bg.append(cost)


    # create a output panda dataframe
df['UnigramCost'] = ug
df['BigramCost'] = bg
df

,Id,Body,CommentCount,LastEditDate,Score,Reputation,UpVotes,DownVotes,Views,QId,...,QBody,BodyLength,InlineCode,BlockCode,BlockCodeLine,Hyperlink,Edit,Label,UnigramCost,BigramCost
0,60026924,<p>You might simplify your piece to make it mo...,2,NaN,0,1678,131,50,109,60012940,...,<p>Given a structure like the following:</p>\n...,17,0,1,3,0,0,1,11.658800,12.166530
1,60013028,"<p>Use <a href=""https://pandas.pydata.org/pand...",0,NaN,0,423,27,14,87,60012972,...,<p>I have a CSV file (<code>data.csv</code>) t...,80,0,4,12,2,0,0,12.274808,12.106733
2,60013049,<p>Solution without <code>pandas</code>:</p>\n...,0,NaN,0,67907,1966,35,5948,60012972,...,<p>I have a CSV file (<code>data.csv</code>) t...,45,1,2,15,0,0,0,13.602454,12.300208
3,60013070,<p>You do not need to load the immense Panda l...,0,2020-02-01 00:55:41,2,695,55,5,87,60012972,...,<p>I have a CSV file (<code>data.csv</code>) t...,90,1,0,0,0,1,0,13.026798,12.129084
4,60013072,<p>Keeping part posters original software</p>\...,0,NaN,1,10876,714,1,925,60012972,...,<p>I have a CSV file (<code>data.csv</code>) t...,40,0,2,12,0,0,1,11.860520,12.019467
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,60022202,<p>Try:</p>\n\n<pre><code>df.groupby(['Gene na...,8,2020-02-03 17:42:01,3,111735,6882,268,5246,60022107,...,"<p>I have this dataframe(df), that looks like ...",208,0,4,19,0,1,1,18.860231,12.853894
316,60022212,"<p>In your function, you're returning prime_fa...",4,NaN,2,640,117,5,68,60022139,...,"<p>I need a little help guys, I'm doing a proj...",31,0,0,0,0,0,1,11.087292,12.155452
317,60022169,<p>Filter out character '-'-containing lines f...,0,NaN,4,6047,467,19,531,60022157,...,<p>I am trying to figure out how to write a fu...,21,0,1,1,0,0,0,11.845983,12.162806
318,60022210,"<p>I'd filter out while reading the file, not ...",0,2020-02-02 00:28:06,2,5574,625,2339,1000,60022157,...,<p>I am trying to figure out how to write a fu...,55,3,1,3,0,1,0,11.781631,12.129351
319,60022273,<p>Gwang-Jin Kim and Heap Overflow answers are...,4,2020-02-02 00:32:34,1,4588,211,39,464,60022157,...,<p>I am trying to figure out how to write a fu...,93,3,1,9,1,1,1,12.007433,12.112167

### Output data

In [34]:
output = df[['Label','Edit','CommentCount','BodyLength', 'Reputation','Views','UpVotes','DownVotes','InlineCode','BlockCode','BlockCodeLine','Hyperlink','UnigramCost','BigramCost']]
output

,Label,Edit,CommentCount,BodyLength,Reputation,Views,UpVotes,DownVotes,InlineCode,BlockCode,BlockCodeLine,Hyperlink,UnigramCost,BigramCost
0,1,0,2,17,1678,109,131,50,0,1,3,0,11.658800,12.166530
1,0,0,0,80,423,87,27,14,0,4,12,2,12.274808,12.106733
2,0,0,0,45,67907,5948,1966,35,1,2,15,0,13.602454,12.300208
3,0,1,0,90,695,87,55,5,1,0,0,0,13.026798,12.129084
4,1,0,0,40,10876,925,714,1,0,2,12,0,11.860520,12.019467
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,1,1,8,208,111735,5246,6882,268,0,4,19,0,18.860231,12.853894
316,1,0,4,31,640,68,117,5,0,0,0,0,11.087292,12.155452
317,0,0,0,21,6047,531,467,19,0,1,1,0,11.845983,12.162806
318,0,1,0,55,5574,1000,625,2339,3,1,3,0,11.781631,12.129351
319,1,1,4,93,4588,464,211,39,3,1,9,1,12.007433,12.112167

In [35]:
output_csv_name = input_csv_name.replace('.csv','_feature.csv')
ofile_name = os.path.join(data_path + os.sep + output_csv_name) #Feature extracted SO data
output.to_csv(ofile_name)