In [1]:
import pandas as pd
import os
import numpy as np

%load_ext autoreload
%autoreload 2

In [2]:
data_path = 'data'
input_csv_name = 'val.csv' 
ifile_name = os.path.join(data_path + os.sep + input_csv_name) #Raw SO scrapped data

In [3]:
df = pd.read_csv(ifile_name)
df

,Id,Body,CommentCount,LastEditDate,Score,Reputation,UpVotes,DownVotes,Views,QId,QAcceptedAnswerId,QBody
0,60026924,<p>You might simplify your piece to make it mo...,2,NaN,0,1678,131,50,109,60012940,60026924,<p>Given a structure like the following:</p>\n...
1,60013028,"<p>Use <a href=""https://pandas.pydata.org/pand...",0,NaN,0,423,27,14,87,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...
2,60013049,<p>Solution without <code>pandas</code>:</p>\n...,0,NaN,0,67907,1966,35,5948,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...
3,60013070,<p>You do not need to load the immense Panda l...,0,2020-02-01 00:55:41,2,695,55,5,87,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...
4,60013072,<p>Keeping part posters original software</p>\...,0,NaN,1,10876,714,1,925,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...
5,60013091,<p>You may use</p>\n\n<pre><code>\b(by|per)\s+...,0,NaN,0,477916,18508,53879,62572,60013016,60013091,<p>I would like a regex to match all character...
6,60013126,<p>I believe it is because some diacritic char...,2,NaN,1,1525,43,4,59,60013043,60016032,<p>Suppose I have the following files in <code...
7,60016032,<p>You can normalize the file list before comp...,1,NaN,1,23288,1366,13,1990,60013043,60016032,<p>Suppose I have the following files in <code...
8,60014046,<p>Can you provide the <code>model.fit</code> ...,0,NaN,0,10363,2079,274,1014,60013061,60014046,<p>Im running a simple neural network interfac...
9,60013154,"<p>I'm not sure if I understood correctly, but...",3,2020-02-01 01:27:45,3,3322,293,58,422,60013125,60013154,<p>I am trying to calculate the values of 2 va...
10,60013327,"<p>Although I have accepted an answer, I think...",2,2020-02-01 15:18:58,0,217,20,0,22,60013125,60013154,<p>I am trying to calculate the values of 2 va...
11,60031662,"<p>Look in the API docs for <a href=""https://d...",0,NaN,0,593,66,0,48,60013135,60031662,<p>How would you make a command that only peop...
12,60013793,<p>In your TodoList model you do not have due_...,1,NaN,2,393,34,1,45,60013141,60013793,<p>I am trying to make a todo-app in Django. I...
13,60014051,<p>You can use a <strong>waiter</strong>:</p>\...,0,NaN,2,161426,2680,33,15860,60013146,60014051,<p>so I'm scheduling an AWS python job (throug...
14,60013609,<p>You are creating an oval one pixel wide and...,3,NaN,1,304622,14209,14165,34310,60013156,60013609,<p>I just started learning <code>tkinter</code...
15,60013333,<p>At first glance it looks like because your ...,0,NaN,0,510,6,3,40,60013290,60013333,"<p>I'm kind of new to python, and I need some ..."
16,60013364,<blockquote>\n <p>if 'word' is in 'minor_word...,0,2020-02-01 02:04:11,1,586865,7069,3864,89361,60013332,60013364,<p>I want to return these results with a def i...
17,60013406,<p><strong>You might also like pandas.</strong...,0,2020-02-01 02:41:23,0,81,3,0,20,60013385,60013434,<p>I'm using Python 3.7. I have an array of d...
18,60013434,"<p>Using <a href=""https://docs.python.org/3/li...",3,2020-02-01 05:52:24,2,30684,4111,819,2869,60013385,60013434,<p>I'm using Python 3.7. I have an array of d...
19,60013596,"<p>Using <code>pandas</code> library, we can u...",0,2020-02-01 11:52:43,1,61,0,0,3,60013459,60013596,<p>I have a dataframe containing 3 columns : <...
20,60013500,<p>It seems like you're setting <code>[toggleL...,0,2020-02-01 02:51:03,0,16,2,0,1,60013461,60013500,"<p>As the title suggests, why can't I stop a w..."
21,60013827,<p>You can use <code>PyAstronomy</code> in pyt...,1,NaN,0,484,430,29,54,60013462,60013827,<p>I'm currently working on period analysis of...
22,60013741,<p>I think you want to use drop_duplicates(). ...,0,NaN,0,145,19,0,9,60013509,60078626,<p>I am scraping some NBA data with Python. I ...
23,60078626,<p>Your doing a ton of work to put a <code>&lt...,0,NaN,0,16881,862,128,1314,60013509,60078626,<p>I am scraping some NBA data with Python. I ...
24,60013923,<p>I tried to <em>stay true</em> to your attem...,12,2020-02-01 16:35:18,0,19459,1049,1547,4170,60013524,60013923,<p>As I mentioned I am attempting to create a ...
25,60021612,<p>Your debug output helpfully contains the fo...,0,2020-02-01 23:00:31,2,3903,717,12,232,60013544,60022248,<p>I am using <code>modbus-tk</code> to serial...
26,60022248,<p>Further to the answer from @maxy; the <a hr...,0,2020-02-04 01:15:53,3,3512,49,44,215,60013544,60022248,<p>I am using <code>modbus-tk</code> to serial...
27,60049315,"<p>Based on the rigor of @maxy's answer, then ...",0,2020-02-04 01:27:30,2,692,525,5,335,60013544,60022248,<p>I am using <code>modbus-tk</code> to serial...
28,60073266,<p>I have the same problem but I know that my ...,2,2020-02-05 10:15:06,1,11,0,0,3,60013544,60022248,<p>I am using <code>modbus-tk</code> to serial...
29,60013737,"<pre><code>cols = ['date_crawled', 'ad_created...",0,NaN,0,800,54,1,57,60013547,60013737,"<pre><code>cols = ['date_crawled', 'ad_created..."
...,...,...,...,...,...,...,...,...,...,...,...,...
290,60021157,<p>If you are reading your data from a csv fil...,1,NaN,2,2271,358,52,360,60021054,60021157,<p>I'm trying to split the dataframe header <c...
291,60024750,<p>Here's a way to do this with a simple SPSS ...,1,NaN,0,8253,1930,18,733,60021100,60024750,<p>I have a list of Baseline and Post variable...
292,60021420,<p>Remove <code>right_ax</code> from everywher...,3,NaN,1,1038,53,6,89,60021324,60021420,"<p>I got this great code example online, it sh..."
293,60022208,<p>Your problem arises because you try to use ...,1,NaN,1,2725,1241,6,266,60021343,60022237,"<p>I deployed Kafka from <a href=""https://gith..."
294,60022237,<p>The topic expects a message in Avro type. <...,7,2020-02-02 00:19:10,1,22983,1501,72,2832,60021343,60022237,"<p>I deployed Kafka from <a href=""https://gith..."
295,60021501,"<p>Maybe you can try this, function isnumeric ...",0,NaN,0,22,0,0,4,60021446,60021504,<p>My code is the following:</p>\n\n<pre><code...
296,60021504,"<p>IIUC, your list kind of gets overwritten as...",0,2020-02-01 22:16:48,3,2271,358,52,360,60021446,60021504,<p>My code is the following:</p>\n\n<pre><code...
297,60021895,<p>Azure Blob Storage it's a good thing to sto...,0,NaN,2,44,0,0,0,60021457,60021895,<p>I am developing a python web application ho...
298,60021603,"<p>You can call the <a href=""https://docs.pyth...",0,NaN,1,312807,16628,2518,41861,60021568,60021603,<p>I saved the datetime in my model and now </...
299,60022979,"<p>Yes, if the main code is in C++ and the bin...",2,NaN,1,2323,67,2,219,60021569,60022979,<p>I have a project where i am mixing cpp and ...
300,60021791,<p>There is a difference between a <code>float...,2,NaN,1,312807,16628,2518,41861,60021577,60021791,"<p>I have a Django model with a FloatField, wh..."
301,63889173,<p>If you really need to use a <code>FloatFiel...,0,2020-09-14 17:37:54,2,21,0,0,3,60021577,60021791,"<p>I have a Django model with a FloatField, wh..."
302,60021696,<p>IIUC for your current example you can try t...,1,NaN,1,2271,358,52,360,60021634,60021696,<p>So I want to add/append data to a specific ...
303,60021811,<p>You need to only subtract <code>m[i]</code>...,0,2020-02-01 23:03:23,1,116404,1598,3075,10590,60021764,60021869,<p>I am trying to delete list from a list of l...
304,60021869,<p>Just a pythonic list comprehension (with <c...,3,NaN,2,5574,625,2339,1000,60021764,60021869,<p>I am trying to delete list from a list of l...
305,60022145,<p>In your views:</p>\n\n<pre><code>if request...,2,2020-02-02 00:14:07,1,6085,3180,0,557,60021784,60022145,<p>I have a custom bootstrap form which is dis...
306,60021917,"<p>Windows, Mac OS and UNIXes code new lines w...",4,2020-02-02 00:20:42,1,4899,456,27,210,60021860,60021917,<p>I'm pretty new to python and linux and I'm ...
307,60022300,<p><strong>If you <code>truncate</code> a file...,1,2020-02-02 00:31:22,2,28324,2387,1411,4522,60021864,60022300,<p>How do I truncate a csv log file that is be...
308,60022076,<p>This is an answer to a similar quesion whic...,4,2020-02-02 13:47:38,0,566,12,2,32,60021927,60022076,"<p>My pandas dataframe ""MSYs"" has a ""start_yr""..."
309,60022164,<p>Although QPainter is used to paint a widget...,1,NaN,3,184341,3940,32065,41961,60021937,60022164,<p>I want to draw a circle that displays over ...
310,60034821,"<p>That's a known PyCharm issue, please vote f...",1,NaN,3,4976,1118,77,415,60021944,60034821,"<p><a href=""https://i.stack.imgur.com/jRXlj.pn..."
311,60022005,<p>You can use a list comprehension :</p>\n\n<...,0,NaN,1,904,133,2,157,60021978,60022005,<p>So if I were to have a list:</p>\n\n<pre><c...
312,60022125,<p>Since the temperature can be between 25 and...,0,2020-02-02 00:03:17,2,26109,745,224,1510,60022040,60022125,<p>I have dataset <code>df</code> as below:</p...
313,60022452,<p>Make sure the time column is in the right f...,3,NaN,1,31,13,0,5,60022040,60022125,<p>I have dataset <code>df</code> as below:</p...
314,60022897,"<p>Do it step by step , <code>numpy.ptp</code>...",1,NaN,2,252249,5881,962,22297,60022040,60022125,<p>I have dataset <code>df</code> as below:</p...
315,60022202,<p>Try:</p>\n\n<pre><code>df.groupby(['Gene na...,8,2020-02-03 17:42:01,3,111735,6882,268,5246,60022107,60022202,"<p>I have this dataframe(df), that looks like ..."
316,60022212,"<p>In your function, you're returning prime_fa...",4,NaN,2,640,117,5,68,60022139,60022212,"<p>I need a little help guys, I'm doing a proj..."
317,60022169,<p>Filter out character '-'-containing lines f...,0,NaN,4,6047,467,19,531,60022157,60022273,<p>I am trying to figure out how to write a fu...
318,60022210,"<p>I'd filter out while reading the file, not ...",0,2020-02-02 00:28:06,2,5574,625,2339,1000,60022157,60022273,<p>I am trying to figure out how to write a fu...
319,60022273,<p>Gwang-Jin Kim and Heap Overflow answers are...,4,2020-02-02 00:32:34,1,4588,211,39,464,60022157,60022273,<p>I am trying to figure out how to write a fu...

### BodyLength
For each answer, we get size of answer body in words

In [4]:
length_list = []
from body_util import clear_tags
datapoints = df.shape[0]
for i in range(datapoints): 
    answer_text = clear_tags(df['Body'][i])
    length_list.append(len(answer_text.split()))

df['BodyLength'] = length_list
df

ImportError: No module named src.body_util

### Code
For each answer, we calculate number of code blocks

In [6]:
codes_inline = []
codes_pre_line = []
codes_pre_count = []
datapoints = df.shape[0]
for i in range(datapoints): 
    answer_text = df['Body'][i]
    code_start = 0
    code_end = 0
    code_pre_line = 0 #Number of code blocks
    code_pre_count = 0 #Number of lines in code blocks
    code_inline = 0 #Number of inline code snippets
    while True:
        code_start = answer_text.find('<code>', code_end)
        if code_start == -1:
            break
        code_end = answer_text.find('</code>', code_start)
        code = answer_text[code_start: code_end+7]
        # Here, code is a string which is of the format <code>.....</code>
        if answer_text[code_start-5: code_start] == '<pre>':
            code_line = code.split('\n')
            code_line_count = len(code_line)-1 # Last line as </code>
            code_pre_line += code_line_count
            code_pre_count += 1
        else:
            code_inline += 1
    codes_inline.append(code_inline)
    codes_pre_line.append(code_pre_line)
    codes_pre_count.append(code_pre_count)

df['InlineCode'] = codes_inline
df['BlockCode'] = codes_pre_count
df['BlockCodeLine'] = codes_pre_line
df

,Id,Body,CommentCount,LastEditDate,Score,Reputation,UpVotes,DownVotes,Views,QId,QAcceptedAnswerId,QBody,InlineCode,BlockCode,BlockCodeLine
0,60026924,<p>You might simplify your piece to make it mo...,2,NaN,0,1678,131,50,109,60012940,60026924,<p>Given a structure like the following:</p>\n...,0,1,3
1,60013028,"<p>Use <a href=""https://pandas.pydata.org/pand...",0,NaN,0,423,27,14,87,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,0,4,12
2,60013049,<p>Solution without <code>pandas</code>:</p>\n...,0,NaN,0,67907,1966,35,5948,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,1,2,15
3,60013070,<p>You do not need to load the immense Panda l...,0,2020-02-01 00:55:41,2,695,55,5,87,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,1,0,0
4,60013072,<p>Keeping part posters original software</p>\...,0,NaN,1,10876,714,1,925,60012972,60013072,<p>I have a CSV file (<code>data.csv</code>) t...,0,2,12
5,60013091,<p>You may use</p>\n\n<pre><code>\b(by|per)\s+...,0,NaN,0,477916,18508,53879,62572,60013016,60013091,<p>I would like a regex to match all character...,14,1,1
6,60013126,<p>I believe it is because some diacritic char...,2,NaN,1,1525,43,4,59,60013043,60016032,<p>Suppose I have the following files in <code...,2,0,0
7,60016032,<p>You can normalize the file list before comp...,1,NaN,1,23288,1366,13,1990,60013043,60016032,<p>Suppose I have the following files in <code...,1,0,0
8,60014046,<p>Can you provide the <code>model.fit</code> ...,0,NaN,0,10363,2079,274,1014,60013061,60014046,<p>Im running a simple neural network interfac...,4,0,0
9,60013154,"<p>I'm not sure if I understood correctly, but...",3,2020-02-01 01:27:45,3,3322,293,58,422,60013125,60013154,<p>I am trying to calculate the values of 2 va...,1,2,12
10,60013327,"<p>Although I have accepted an answer, I think...",2,2020-02-01 15:18:58,0,217,20,0,22,60013125,60013154,<p>I am trying to calculate the values of 2 va...,0,2,9
11,60031662,"<p>Look in the API docs for <a href=""https://d...",0,NaN,0,593,66,0,48,60013135,60031662,<p>How would you make a command that only peop...,0,0,0
12,60013793,<p>In your TodoList model you do not have due_...,1,NaN,2,393,34,1,45,60013141,60013793,<p>I am trying to make a todo-app in Django. I...,0,0,0
13,60014051,<p>You can use a <strong>waiter</strong>:</p>\...,0,NaN,2,161426,2680,33,15860,60013146,60014051,<p>so I'm scheduling an AWS python job (throug...,2,0,0
14,60013609,<p>You are creating an oval one pixel wide and...,3,NaN,1,304622,14209,14165,34310,60013156,60013609,<p>I just started learning <code>tkinter</code...,2,1,14
15,60013333,<p>At first glance it looks like because your ...,0,NaN,0,510,6,3,40,60013290,60013333,"<p>I'm kind of new to python, and I need some ...",2,1,13
16,60013364,<blockquote>\n <p>if 'word' is in 'minor_word...,0,2020-02-01 02:04:11,1,586865,7069,3864,89361,60013332,60013364,<p>I want to return these results with a def i...,10,2,2
17,60013406,<p><strong>You might also like pandas.</strong...,0,2020-02-01 02:41:23,0,81,3,0,20,60013385,60013434,<p>I'm using Python 3.7. I have an array of d...,1,0,0
18,60013434,"<p>Using <a href=""https://docs.python.org/3/li...",3,2020-02-01 05:52:24,2,30684,4111,819,2869,60013385,60013434,<p>I'm using Python 3.7. I have an array of d...,3,4,14
19,60013596,"<p>Using <code>pandas</code> library, we can u...",0,2020-02-01 11:52:43,1,61,0,0,3,60013459,60013596,<p>I have a dataframe containing 3 columns : <...,11,4,14
20,60013500,<p>It seems like you're setting <code>[toggleL...,0,2020-02-01 02:51:03,0,16,2,0,1,60013461,60013500,"<p>As the title suggests, why can't I stop a w...",8,0,0
21,60013827,<p>You can use <code>PyAstronomy</code> in pyt...,1,NaN,0,484,430,29,54,60013462,60013827,<p>I'm currently working on period analysis of...,1,2,5
22,60013741,<p>I think you want to use drop_duplicates(). ...,0,NaN,0,145,19,0,9,60013509,60078626,<p>I am scraping some NBA data with Python. I ...,0,3,13
23,60078626,<p>Your doing a ton of work to put a <code>&lt...,0,NaN,0,16881,862,128,1314,60013509,60078626,<p>I am scraping some NBA data with Python. I ...,1,2,38
24,60013923,<p>I tried to <em>stay true</em> to your attem...,12,2020-02-01 16:35:18,0,19459,1049,1547,4170,60013524,60013923,<p>As I mentioned I am attempting to create a ...,1,2,33
25,60021612,<p>Your debug output helpfully contains the fo...,0,2020-02-01 23:00:31,2,3903,717,12,232,60013544,60022248,<p>I am using <code>modbus-tk</code> to serial...,0,1,2
26,60022248,<p>Further to the answer from @maxy; the <a hr...,0,2020-02-04 01:15:53,3,3512,49,44,215,60013544,60022248,<p>I am using <code>modbus-tk</code> to serial...,4,0,0
27,60049315,"<p>Based on the rigor of @maxy's answer, then ...",0,2020-02-04 01:27:30,2,692,525,5,335,60013544,60022248,<p>I am using <code>modbus-tk</code> to serial...,6,0,0
28,60073266,<p>I have the same problem but I know that my ...,2,2020-02-05 10:15:06,1,11,0,0,3,60013544,60022248,<p>I am using <code>modbus-tk</code> to serial...,0,2,14
29,60013737,"<pre><code>cols = ['date_crawled', 'ad_created...",0,NaN,0,800,54,1,57,60013547,60013737,"<pre><code>cols = ['date_crawled', 'ad_created...",0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290,60021157,<p>If you are reading your data from a csv fil...,1,NaN,2,2271,358,52,360,60021054,60021157,<p>I'm trying to split the dataframe header <c...,2,2,5
291,60024750,<p>Here's a way to do this with a simple SPSS ...,1,NaN,0,8253,1930,18,733,60021100,60024750,<p>I have a list of Baseline and Post variable...,0,2,19
292,60021420,<p>Remove <code>right_ax</code> from everywher...,3,NaN,1,1038,53,6,89,60021324,60021420,"<p>I got this great code example online, it sh...",2,1,36
293,60022208,<p>Your problem arises because you try to use ...,1,NaN,1,2725,1241,6,266,60021343,60022237,"<p>I deployed Kafka from <a href=""https://gith...",4,2,8
294,60022237,<p>The topic expects a message in Avro type. <...,7,2020-02-02 00:19:10,1,22983,1501,72,2832,60021343,60022237,"<p>I deployed Kafka from <a href=""https://gith...",2,1,63
295,60021501,"<p>Maybe you can try this, function isnumeric ...",0,NaN,0,22,0,0,4,60021446,60021504,<p>My code is the following:</p>\n\n<pre><code...,0,1,7
296,60021504,"<p>IIUC, your list kind of gets overwritten as...",0,2020-02-01 22:16:48,3,2271,358,52,360,60021446,60021504,<p>My code is the following:</p>\n\n<pre><code...,1,5,27
297,60021895,<p>Azure Blob Storage it's a good thing to sto...,0,NaN,2,44,0,0,0,60021457,60021895,<p>I am developing a python web application ho...,0,0,0
298,60021603,"<p>You can call the <a href=""https://docs.pyth...",0,NaN,1,312807,16628,2518,41861,60021568,60021603,<p>I saved the datetime in my model and now </...,1,1,3
299,60022979,"<p>Yes, if the main code is in C++ and the bin...",2,NaN,1,2323,67,2,219,60021569,60022979,<p>I have a project where i am mixing cpp and ...,15,7,14
300,60021791,<p>There is a difference between a <code>float...,2,NaN,1,312807,16628,2518,41861,60021577,60021791,"<p>I have a Django model with a FloatField, wh...",9,1,9
301,63889173,<p>If you really need to use a <code>FloatFiel...,0,2020-09-14 17:37:54,2,21,0,0,3,60021577,60021791,"<p>I have a Django model with a FloatField, wh...",3,1,8
302,60021696,<p>IIUC for your current example you can try t...,1,NaN,1,2271,358,52,360,60021634,60021696,<p>So I want to add/append data to a specific ...,1,4,24
303,60021811,<p>You need to only subtract <code>m[i]</code>...,0,2020-02-01 23:03:23,1,116404,1598,3075,10590,60021764,60021869,<p>I am trying to delete list from a list of l...,7,2,6
304,60021869,<p>Just a pythonic list comprehension (with <c...,3,NaN,2,5574,625,2339,1000,60021764,60021869,<p>I am trying to delete list from a list of l...,1,1,1
305,60022145,<p>In your views:</p>\n\n<pre><code>if request...,2,2020-02-02 00:14:07,1,6085,3180,0,557,60021784,60022145,<p>I have a custom bootstrap form which is dis...,6,2,17
306,60021917,"<p>Windows, Mac OS and UNIXes code new lines w...",4,2020-02-02 00:20:42,1,4899,456,27,210,60021860,60021917,<p>I'm pretty new to python and linux and I'm ...,8,0,0
307,60022300,<p><strong>If you <code>truncate</code> a file...,1,2020-02-02 00:31:22,2,28324,2387,1411,4522,60021864,60022300,<p>How do I truncate a csv log file that is be...,9,0,0
308,60022076,<p>This is an answer to a similar quesion whic...,4,2020-02-02 13:47:38,0,566,12,2,32,60021927,60022076,"<p>My pandas dataframe ""MSYs"" has a ""start_yr""...",0,1,25
309,60022164,<p>Although QPainter is used to paint a widget...,1,NaN,3,184341,3940,32065,41961,60021937,60022164,<p>I want to draw a circle that displays over ...,1,0,0
310,60034821,"<p>That's a known PyCharm issue, please vote f...",1,NaN,3,4976,1118,77,415,60021944,60034821,"<p><a href=""https://i.stack.imgur.com/jRXlj.pn...",0,0,0
311,60022005,<p>You can use a list comprehension :</p>\n\n<...,0,NaN,1,904,133,2,157,60021978,60022005,<p>So if I were to have a list:</p>\n\n<pre><c...,0,1,1
312,60022125,<p>Since the temperature can be between 25 and...,0,2020-02-02 00:03:17,2,26109,745,224,1510,60022040,60022125,<p>I have dataset <code>df</code> as below:</p...,3,1,16
313,60022452,<p>Make sure the time column is in the right f...,3,NaN,1,31,13,0,5,60022040,60022125,<p>I have dataset <code>df</code> as below:</p...,0,4,6
314,60022897,"<p>Do it step by step , <code>numpy.ptp</code>...",1,NaN,2,252249,5881,962,22297,60022040,60022125,<p>I have dataset <code>df</code> as below:</p...,2,1,7
315,60022202,<p>Try:</p>\n\n<pre><code>df.groupby(['Gene na...,8,2020-02-03 17:42:01,3,111735,6882,268,5246,60022107,60022202,"<p>I have this dataframe(df), that looks like ...",0,4,19
316,60022212,"<p>In your function, you're returning prime_fa...",4,NaN,2,640,117,5,68,60022139,60022212,"<p>I need a little help guys, I'm doing a proj...",0,0,0
317,60022169,<p>Filter out character '-'-containing lines f...,0,NaN,4,6047,467,19,531,60022157,60022273,<p>I am trying to figure out how to write a fu...,0,1,1
318,60022210,"<p>I'd filter out while reading the file, not ...",0,2020-02-02 00:28:06,2,5574,625,2339,1000,60022157,60022273,<p>I am trying to figure out how to write a fu...,3,1,3
319,60022273,<p>Gwang-Jin Kim and Heap Overflow answers are...,4,2020-02-02 00:32:34,1,4588,211,39,464,60022157,60022273,<p>I am trying to figure out how to write a fu...,3,1,9

### Hyperlink
For each post, we calculate the number of links referenced

In [ ]:
hyperlinks = []
datapoints = df.shape[0]
for i in range(datapoints):
    body = df['Body'][i]
    hyperlink_pos = -1
    hyperlink = 0
    while True:
        hyperlink_pos = body.find('<a href=', hyperlink_pos+1)
        if hyperlink_pos == -1:
            break
        hyperlink += 1
        # print(i, body[hyperlink_pos:hyperlink_pos + 50])
    hyperlinks.append(hyperlink)

df['Hyperlink'] = hyperlinks
df

### Edit
For each post, we check if it was edited

In [ ]:
edits = []
datapoints = df.shape[0]
for i in range(datapoints):
    last_edit_date = df['LastEditDate'][i] # str or float (np.nan)
    if isinstance(last_edit_date, float):
        if np.isnan(last_edit_date):
            edits.append('0')
        else:
            edits.append('1')
    else:
        edits.append('1')
df['Edit'] = edits
df

### Label
For each post, we classify if it is the correct answer

In [ ]:
labels = []
datapoints = df.shape[0]
for i in range(datapoints):
        
    answer_id = df['Id'][i] # int
    accepted_id = df['QAcceptedAnswerId'][i] # float (np.nan)
    if np.isnan(accepted_id):
        labels.append(np.nan)
    else:
        if answer_id == int(accepted_id):
            labels.append('1')
        else:
            labels.append('0')
df['Label'] = labels
df

### Unigram + Bigram scores
First, we generate a corpus of well written answers

In [ ]:
from ngram import gen_corpus
from os.path import exists

corpus_file = 'data/corpus.txt' #This is the output which will be generated
if input_csv_name == 'train.csv':
    gen_corpus(df[df.Label=='1'].Body.tolist(),corpus_file)
else:
    print ("NGram corpus only for train data")
    if not exists(corpus_file):
        raise Exception("No corpus present. Generate corpus with training data first")

Now, we use the corpus file to generate a language model. Then we can calculate unigram and bigram costs

In [ ]:
from ngram import make_language_model
from ngram import SENTENCE_BEGIN

unigram_cost, bigram_cost = make_language_model(corpus_file)

ug = []
bg = []

datapoints = df.shape[0]

for i in range(datapoints):
        line = df['Body'][i]
        # Unigram cost.
        grams=tuple(line)
        cost=0
        for j in range(len(grams)):
            cost+=unigram_cost(grams[j])
        cost=cost/len(grams)
        ug.append(cost)

        cost=bigram_cost(SENTENCE_BEGIN, grams[0])
        for j in range(1,len(grams)):
            cost+=bigram_cost(grams[j-1], grams[j])
        cost=cost/len(grams)
        bg.append(cost)


    # create a output panda dataframe
df['UnigramCost'] = ug
df['BigramCost'] = bg
df

### Output data

In [ ]:
output = df[['Label','Edit','CommentCount','BodyLength', 'Reputation','Views','UpVotes','DownVotes','InlineCode','BlockCode','BlockCodeLine','Hyperlink','UnigramCost','BigramCost']]
output

In [ ]:
output_csv_name = input_csv_name.replace('.csv','_feature.csv')
ofile_name = os.path.join(data_path + os.sep + output_csv_name) #Feature extracted SO data
output.to_csv(ofile_name)